### ISSUE TITLE
Suggestion : Google App Engine Node.js "Standard" is now in beta

### ISSUE THREAD

**Issue by kylecordes** [fusionstrings/firebase-functions-sapper#1]
Hello. This is a very slick example, deploying a Snapper application and outside Firebase Functions.

But, I think the new GAE support for Node applications in the "standard" environment, is probably a better fit semantically for Sapper. I'm using it this way myself in a small example, with no trouble at all. And it needs **considerably less rearrangement** than this example did, really just a few files (.gcloudignore, app.yaml), minor edits to the package.json, etc.

**Comment by fusionstrings** [comment]
Hi @kylecordes ,
Thanks for looking at it.

I value your suggestions, in fact, my own app is hosted on GAE. 

I still wanted to make it for the following reasons.

This example is similar to one of these https://github.com/firebase/functions-samples
People trying to adopt https://github.com/sveltejs/sapper might have a use case.

GAE standard still requires you to add billing to projects. Google Cloud billing just alerts you, not stop at the threshold.

Firebase functions don't have this limitation. People may fork and deploy on will.

**Comment by kylecordes** [comment]
@fusionstrings This is a very interesting difference I had not noticed, you can deploy (low-volume) Functions on the free tier without enabling billing!
